name: My First Workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: checkoot repo
              uses: actions/checkout@v4
            - name: welcome message
              run: echo "first message"
            - name: List Files
              run: ls
            - name: Read file
              run: cat README.md
