name: Generate Ascii text

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: list repo files
          run:  ls -ltra

        - name: executing shell script
          run: |
            chmod  +x  generate-asc-script
            ./generate-asc-script

          
            